/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentTutorRouteImport } from './routes/student.tutor'
import { Route as StudentQuizzesRouteImport } from './routes/student.quizzes'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentLeaderboardRouteImport } from './routes/student.leaderboard'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as InstructorStudentsRouteImport } from './routes/instructor.students'
import { Route as InstructorGradingRouteImport } from './routes/instructor.grading'
import { Route as InstructorDashboardRouteImport } from './routes/instructor.dashboard'
import { Route as InstructorContentRouteImport } from './routes/instructor.content'
import { Route as InstructorAnalyticsRouteImport } from './routes/instructor.analytics'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as StudentCoursesIdRouteImport } from './routes/student.courses.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentTutorRoute = StudentTutorRouteImport.update({
  id: '/student/tutor',
  path: '/student/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentQuizzesRoute = StudentQuizzesRouteImport.update({
  id: '/student/quizzes',
  path: '/student/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/student/progress',
  path: '/student/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLeaderboardRoute = StudentLeaderboardRouteImport.update({
  id: '/student/leaderboard',
  path: '/student/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/student/courses',
  path: '/student/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorStudentsRoute = InstructorStudentsRouteImport.update({
  id: '/instructor/students',
  path: '/instructor/students',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorGradingRoute = InstructorGradingRouteImport.update({
  id: '/instructor/grading',
  path: '/instructor/grading',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorDashboardRoute = InstructorDashboardRouteImport.update({
  id: '/instructor/dashboard',
  path: '/instructor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorContentRoute = InstructorContentRouteImport.update({
  id: '/instructor/content',
  path: '/instructor/content',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorAnalyticsRoute = InstructorAnalyticsRouteImport.update({
  id: '/instructor/analytics',
  path: '/instructor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesIdRoute = StudentCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/content': typeof InstructorContentRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/grading': typeof InstructorGradingRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/student/tutor': typeof StudentTutorRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/content': typeof InstructorContentRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/grading': typeof InstructorGradingRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/student/tutor': typeof StudentTutorRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/content': typeof InstructorContentRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/grading': typeof InstructorGradingRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/student/tutor': typeof StudentTutorRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/announcements'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/users'
    | '/instructor/analytics'
    | '/instructor/content'
    | '/instructor/dashboard'
    | '/instructor/grading'
    | '/instructor/students'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/leaderboard'
    | '/student/progress'
    | '/student/quizzes'
    | '/student/tutor'
    | '/student/courses/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/announcements'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/users'
    | '/instructor/analytics'
    | '/instructor/content'
    | '/instructor/dashboard'
    | '/instructor/grading'
    | '/instructor/students'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/leaderboard'
    | '/student/progress'
    | '/student/quizzes'
    | '/student/tutor'
    | '/student/courses/$id'
  id:
    | '__root__'
    | '/'
    | '/admin/announcements'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/admin/users'
    | '/instructor/analytics'
    | '/instructor/content'
    | '/instructor/dashboard'
    | '/instructor/grading'
    | '/instructor/students'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/leaderboard'
    | '/student/progress'
    | '/student/quizzes'
    | '/student/tutor'
    | '/student/courses/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  InstructorAnalyticsRoute: typeof InstructorAnalyticsRoute
  InstructorContentRoute: typeof InstructorContentRoute
  InstructorDashboardRoute: typeof InstructorDashboardRoute
  InstructorGradingRoute: typeof InstructorGradingRoute
  InstructorStudentsRoute: typeof InstructorStudentsRoute
  StudentCoursesRoute: typeof StudentCoursesRouteWithChildren
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentLeaderboardRoute: typeof StudentLeaderboardRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentQuizzesRoute: typeof StudentQuizzesRoute
  StudentTutorRoute: typeof StudentTutorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/tutor': {
      id: '/student/tutor'
      path: '/student/tutor'
      fullPath: '/student/tutor'
      preLoaderRoute: typeof StudentTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/quizzes': {
      id: '/student/quizzes'
      path: '/student/quizzes'
      fullPath: '/student/quizzes'
      preLoaderRoute: typeof StudentQuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/student/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/leaderboard': {
      id: '/student/leaderboard'
      path: '/student/leaderboard'
      fullPath: '/student/leaderboard'
      preLoaderRoute: typeof StudentLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/student/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/students': {
      id: '/instructor/students'
      path: '/instructor/students'
      fullPath: '/instructor/students'
      preLoaderRoute: typeof InstructorStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/grading': {
      id: '/instructor/grading'
      path: '/instructor/grading'
      fullPath: '/instructor/grading'
      preLoaderRoute: typeof InstructorGradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/dashboard': {
      id: '/instructor/dashboard'
      path: '/instructor/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof InstructorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/content': {
      id: '/instructor/content'
      path: '/instructor/content'
      fullPath: '/instructor/content'
      preLoaderRoute: typeof InstructorContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/analytics': {
      id: '/instructor/analytics'
      path: '/instructor/analytics'
      fullPath: '/instructor/analytics'
      preLoaderRoute: typeof InstructorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses/$id': {
      id: '/student/courses/$id'
      path: '/$id'
      fullPath: '/student/courses/$id'
      preLoaderRoute: typeof StudentCoursesIdRouteImport
      parentRoute: typeof StudentCoursesRoute
    }
  }
}

interface StudentCoursesRouteChildren {
  StudentCoursesIdRoute: typeof StudentCoursesIdRoute
}

const StudentCoursesRouteChildren: StudentCoursesRouteChildren = {
  StudentCoursesIdRoute: StudentCoursesIdRoute,
}

const StudentCoursesRouteWithChildren = StudentCoursesRoute._addFileChildren(
  StudentCoursesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  InstructorAnalyticsRoute: InstructorAnalyticsRoute,
  InstructorContentRoute: InstructorContentRoute,
  InstructorDashboardRoute: InstructorDashboardRoute,
  InstructorGradingRoute: InstructorGradingRoute,
  InstructorStudentsRoute: InstructorStudentsRoute,
  StudentCoursesRoute: StudentCoursesRouteWithChildren,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentLeaderboardRoute: StudentLeaderboardRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentQuizzesRoute: StudentQuizzesRoute,
  StudentTutorRoute: StudentTutorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
